### ISSUE TITLE
Bug in calculating Aspect-level Certainty

### ISSUE THREAD

**Issue by mallaham** [Jiaxin-Pei/certainty-estimator#2]
Upon following and testing the steps to estimate aspect-level uncertainty, per the README (https://github.com/Jiaxin-Pei/certainty-estimator#estimating-aspect-level-certainty), the code is throwing an error: "Value Error axes don't match array". Verifying the model uploaded on huggingface then checking the dimensions of the predictions in line [115](https://github.com/Jiaxin-Pei/certainty-estimator/blob/871d17613c4fb2500fe40745b74d3fc25a8b8e9b/certainty_estimator/predict_certainty.py#L115) and line [126](https://github.com/Jiaxin-Pei/certainty-estimator/blob/871d17613c4fb2500fe40745b74d3fc25a8b8e9b/certainty_estimator/predict_certainty.py#L126) would be a good start.

**Comment by Jiaxin-Pei** [comment]
Thanks for reporting this issue!
I just checked that the uploaded model is correct and it works well on my machines. Would it be possible for you to provide more details on your system environment (especially python and transformers version) and how you are running this? Did you try to run the play.py in this repo?

**Comment by mallaham** [comment]
Hi @Jiaxin-Pei , I'm using a mac machine and tested the code both in python CLI and jupyternotebook using python 3.7. Below are versions for the packages:

- Transformers 4.14.1
- Torch 1.10.1
- Python 3.7.7

FYI, I also had to replace `from .edited_bert import BertForSequenceClassification` with `from transformers import BertModel,BertForSequenceClassification` because when importing from `.edited_bert` I get the following error:  `TypeError: add_code_sample_docstrings() got an unexpected keyword argument 'tokenizer_class'`. This error presisted even when running `play.py` script. When substituting the import from `.edited_bert` with `transformers` the error is resolved, but another error shows up `ValueError: axes don't match array`.

**Comment by mallaham** [comment]
@Jiaxin-Pei , okay issue resolved. I commented out the docs decorator from `edited_bert.py` and the script seems to be working fine! :)

**Comment by mallaham** [comment]
Created a pull request for review: https://github.com/Jiaxin-Pei/certainty-estimator/pull/3

**Comment by Jiaxin-Pei** [comment]
Thanks a lot for help identifying the issue! Please note that we edited the standard BertForSequenceClassification to allow joint prediction for 6 aspects of certainty (basically 6 classification heads instead of only one) and that's why you got the 
`ValueError: axes don't match array` error. 

The docs decorator issue was due to some recent updates of the hugging face transformers that I wasn't aware of. Thanks a lot for identifying it and submitting the pull request!
